### PR TITLE
Wishlist Page

### LINKED ISSUE #5: Button Padding and Deploy Preview Unavailability
### Issue Description:
- The padding of the button in the mobile view needs adjustment. Currently, it appears to have excessive padding, which affects the overall design and user experience.
- Furthermore, when reloading the deploy preview, it becomes unavailable, causing inconvenience and hindering the review process.

### To address these issues, the following actions should be taken:
- Adjust the button padding in the mobile view to provide a better visual and interactive experience for users.
Investigate and resolve the issue causing the deploy preview to become unavailable upon reloading.
- To assist with resolving the deploy preview unavailability, it would be helpful to add a redirects file that handles the necessary routing. This file should ensure the correct redirection and availability of the deploy preview upon reloading.

### PR DESCRIPTION
**Pull request by chhakuli123**
- Created the Wishlist page component, including the necessary UI elements and functionality.
- Implemented the wishlist creation feature, allowing users to add and delete multiple products in wishlists.
- Added the ability for users to add items to their wishlists with details such as name, description, image, price, and notes.

### CODE REVIEW

**Review by prajwalzingare — CHANGES_REQUESTED** [review]
- fix the padding of a button in the mobile view
image

-  Add redirects File because on reloading deploy preview is not Avaialabel

**Comment by chhakuli123** [comment]
> * fix the padding of a button in the mobile view
> 
> image
> * Add redirects File because on reloading deploy preview is not available

Resolved the issue of padding and deploy.Thanks for finding bug and reviewing my project.

**Comment by prajwalzingare** [comment]
> > * fix the padding of a button in the mobile view
> > 
> > image
> > * Add redirects File because on reloading deploy preview is not available
> 
> Resolved the issue of padding and deploy.Thanks for finding bug and reviewing my project.

Great job! Everything looks fantastic, and the wishlist feature is working perfectly. 👌🎉

I've thoroughly tested it, and all functionalities are functioning as expected. The wishlist allows users to add items, remove items, and the UI is user-friendly and intuitive.

**Review by prajwalzingare — APPROVED** [review]
Great job! Everything looks fantastic, and the wishlist feature is working perfectly. 👌🎉

I've thoroughly tested it, and all functionalities are functioning as expected. The wishlist allows users to add items, remove items, and the UI is user-friendly and intuitive.

**Pull request merged**
