### PR TITLE
Cart page

### PR DESCRIPTION
**Pull request by chhakuli123**
### Cart Page Development: 
-  Implemented Quantity selection, Applied discounts, Apply Coupon with Coupon Modal.
-  Responsive UI. 
-  Implemented move to wishlist and remove item functionality.
-  Fixed bugs and optimized code for better performance. 
### Please review and provide feedback🙏

### CODE REVIEW

**Review by Kavita539 — APPROVED** [review]
-Loved the code structure
-Nicely written code
-Great work on UI

**Comment by chhakuli123** [comment]
> -Loved the code structure -Nicely written code -Great work on UI

Thank you so much for taking the time and reviewing the code.

**Review by prajwalzingare — CHANGES_REQUESTED** [review]
- fix notification when there is no quantity decrease after one 
- rest is looking fine

**Comment by chhakuli123** [comment]
> * fix notification when there is no quantity decrease after one
> * rest is looking fine

I fixed the issue.Thank you so much for taking the time and reviewing my PR.

**Review by prajwalzingare — APPROVED** [review]
- All changes have been implemented successfully and thoroughly reviewed. The code is clean, follows best practices, and aligns with the project requirements. 
- Ready to merge

**Pull request merged**
