### PR TITLE
Products page

### PR DESCRIPTION
**Pull request by chhakuli123**

### CODE REVIEW

**Comment by prajwalzingare** [comment]
-on each hover of the filter you should add cursor: pointer
everything looks fine otherwise.

**Review by prajwalzingare — APPROVED** [review]
On each hover of the filter label, the cursor should be set to the pointer.
Everything else looks fine. You can proceed with merging the branch.

**Comment by chhakuli123** [comment]
Thanks

**Comment by prajwalzingare** [comment]
- The overall structure of the codebase is well-organized and follows a modular approach, which is great for maintainability and scalability.
- The naming conventions used throughout the codebase are clear and descriptive, making it easier to understand the purpose of variables, functions, and modules.
- The code is properly separated into different modules and functions, ensuring a clear separation of concerns and improving code reusability.

**Pull request merged**
